/**
 * `@konusbitr/sdk` — the TypeScript client for the Konusbitr API.
 *
 * ```ts
 * import { KonusbitrClient } from '@konusbitr/sdk';
 *
 * const konusbitr = new KonusbitrClient({
 *   baseUrl: 'https://konusbitr.example.com',
 *   apiKey: process.env.KONUSBITR_API_KEY!,
 * });
 *
 * const { docId } = await konusbitr.parse({ url: 'https://example.com/report.pdf' });
 * const { answer, citations } = await konusbitr.ask({ docId, question: 'What is the total?' });
 * ```
 *
 * The types and the operation table under `generated/` come from the API's own
 * OpenAPI document and are regenerated by `pnpm --filter @konusbitr/sdk
 * generate`; CI fails on drift. The client itself is written by hand, because
 * retries, backoff and job polling are not things a specification describes.
 */

export { type ClientOptions, KonusbitrClient } from './client.js';
export { JobFailedError, KonusbitrError, RateLimitError } from './errors.js';
export { API_VERSION } from './generated/operations.js';
export type * from './generated/types.js';
