"""Fixtures built on the doubles in :mod:`tests.factories`."""

from __future__ import annotations

from pathlib import Path
from typing import Any

import pytest

from konusbitr_worker.contracts import JobStage
from konusbitr_worker.parse import BatchOutcome
from konusbitr_worker.parse.artifact import (
    ElementType,
    ParseArtifact,
    ParsedElement,
    ParsedPage,
)
from konusbitr_worker.parse.geometry import BBox
from konusbitr_worker.settings import Settings
from tests.factories import BASE_ENV, FakeQueue


@pytest.fixture
def settings() -> Settings:
    """Settings with every wait turned down, so the tests are instant."""
    return Settings(
        _env_file=None,
        worker_parse_threads=4,
        worker_retry_base_seconds=1.0,
        worker_max_attempts=3,
        worker_concurrency=2,
        **BASE_ENV,
    )


@pytest.fixture
def queue() -> FakeQueue:
    return FakeQueue()


@pytest.fixture(scope="session")
def fixtures_dir() -> Path:
    """The committed PDF corpus. Generated by `fixtures/generate.py`, never scraped."""
    directory = Path(__file__).resolve().parents[3] / "fixtures" / "pdf"
    if not directory.is_dir():  # pragma: no cover - a broken checkout
        pytest.skip(f"the fixture corpus is missing from {directory}")
    return directory


@pytest.fixture
def artifact() -> ParseArtifact:
    """A parse result, without a parser. Stands in for whatever Docling returns.

    `contents` is populated because the chunker is downstream of it: a fixture
    with an empty element list would let every chunking assertion pass by
    producing nothing.
    """
    return ParseArtifact(
        markdown="# Title\n\nRevenue grew 18% year over year.\n",
        page_count=2,
        contents=[
            ParsedElement(
                id="el_0000",
                type=ElementType.heading,
                text="Title",
                markdown="# Title",
                page=1,
                bbox=BBox(72.0, 72.0, 540.0, 92.0),
                level=1,
            ),
            ParsedElement(
                id="el_0001",
                type=ElementType.paragraph,
                text="Revenue grew 18% year over year.",
                markdown="Revenue grew 18% year over year.",
                page=1,
                bbox=BBox(72.0, 100.0, 540.0, 140.0),
                section_path=["Title"],
            ),
            ParsedElement(
                id="el_0002",
                type=ElementType.paragraph,
                text="Costs were flat against a rising headcount.",
                markdown="Costs were flat against a rising headcount.",
                page=2,
                bbox=BBox(72.0, 100.0, 540.0, 150.0),
                section_path=["Title"],
            ),
        ],
        pages=[
            ParsedPage(page_no=1, width=612.0, height=792.0, thumbnail_key="thumb/1.webp"),
            ParsedPage(page_no=2, width=841.89, height=595.28, rotation=90),
        ],
    )


@pytest.fixture
def stub_parse(monkeypatch: pytest.MonkeyPatch, artifact: ParseArtifact) -> list[dict[str, Any]]:
    """Replace the parse with a recorder, leaving the orchestration real.

    The double reports **one batch covering the whole document**, which is
    exactly what the real parse does for anything shorter than
    `WORKER_PAGE_BATCH_SIZE` — the shape almost every upload has. That matters
    more than it looks: the commit callback is where the pipeline persists the
    artifact, writes the page rows, indexes the chunks and clears the
    checkpoint, so a double that skipped it would leave every orchestration
    test asserting against a database nothing had written to.
    """
    calls: list[dict[str, Any]] = []

    async def fake_parse(**kwargs: Any) -> ParseArtifact:
        calls.append(kwargs)
        on_stage = kwargs.get("on_stage")
        if on_stage is not None:
            for stage in (JobStage.fetching, JobStage.validating, JobStage.parsing):
                await on_stage(stage)

        on_batch = kwargs.get("on_batch")
        if on_batch is not None:
            await on_batch(
                BatchOutcome(
                    first_page=1,
                    last_page=artifact.page_count,
                    elements=list(artifact.contents),
                    artifact=artifact,
                    pages_done=artifact.page_count,
                    page_count=artifact.page_count,
                    chunks_written=0,
                )
            )
        return artifact

    monkeypatch.setattr("konusbitr_worker.pipeline.parse_document", fake_parse)
    return calls
