"""Fixtures built on the doubles in :mod:`tests.factories`."""

from __future__ import annotations

from pathlib import Path
from typing import Any

import pytest

from konusbitr_worker.contracts import JobStage
from konusbitr_worker.parse.artifact import ParseArtifact, ParsedPage
from konusbitr_worker.settings import Settings
from tests.factories import BASE_ENV, FakeQueue


@pytest.fixture
def settings() -> Settings:
    """Settings with every wait turned down, so the tests are instant."""
    return Settings(
        _env_file=None,
        worker_parse_threads=4,
        worker_retry_base_seconds=1.0,
        worker_max_attempts=3,
        worker_concurrency=2,
        **BASE_ENV,
    )


@pytest.fixture
def queue() -> FakeQueue:
    return FakeQueue()


@pytest.fixture(scope="session")
def fixtures_dir() -> Path:
    """The committed PDF corpus. Generated by `fixtures/generate.py`, never scraped."""
    directory = Path(__file__).resolve().parents[3] / "fixtures" / "pdf"
    if not directory.is_dir():  # pragma: no cover - a broken checkout
        pytest.skip(f"the fixture corpus is missing from {directory}")
    return directory


@pytest.fixture
def artifact() -> ParseArtifact:
    """A parse result, without a parser. Stands in for whatever Docling returns."""
    return ParseArtifact(
        markdown="# Title\n\nRevenue grew 18% year over year.\n",
        page_count=2,
        contents=[],
        pages=[
            ParsedPage(page_no=1, width=612.0, height=792.0, thumbnail_key="thumb/1.webp"),
            ParsedPage(page_no=2, width=841.89, height=595.28, rotation=90),
        ],
    )


@pytest.fixture
def stub_parse(monkeypatch: pytest.MonkeyPatch, artifact: ParseArtifact) -> list[dict[str, Any]]:
    """Replace the parse with a recorder, leaving the orchestration real."""
    calls: list[dict[str, Any]] = []

    async def fake_parse(**kwargs: Any) -> ParseArtifact:
        calls.append(kwargs)
        on_stage = kwargs.get("on_stage")
        if on_stage is not None:
            for stage in (
                JobStage.fetching,
                JobStage.validating,
                JobStage.parsing,
                JobStage.persisting,
            ):
                await on_stage(stage)
        return artifact

    monkeypatch.setattr("konusbitr_worker.pipeline.parse_document", fake_parse)
    return calls
