"""The real parser over the real corpus.

Everything else in this suite tests a decision in isolation. This file tests
the claim: that a text PDF goes in and faithful markdown plus locatable
elements come out. It is the slowest thing in the repository and the only thing
that would notice Docling changing its mind about a label, an origin, or a
reading order — so it runs in CI on every change and is marked `slow` so that a
developer can skip it while iterating on something else.

Fixtures are generated by `fixtures/generate.py`, which means the expected
output is *known* rather than merely recorded: the assertions below are against
strings this repository put into those documents.

Golden files live in `tests/golden/` and are compared after whitespace
normalization, because a parser is allowed to change how it wraps a line and is
not allowed to change what the line says. Regenerate them deliberately with
`KONUSBITR_UPDATE_GOLDEN=1 uv run pytest tests/test_parse_fixtures.py`, and read
the diff — a golden file updated without reading the diff is a test that has
been switched off.
"""

from __future__ import annotations

import os
import re
import time
from pathlib import Path

import pytest

from konusbitr_worker.contracts import JobErrorCode
from konusbitr_worker.errors import JobFailure
from konusbitr_worker.parse import parse_document
from konusbitr_worker.parse.artifact import ElementType, ParseArtifact
from konusbitr_worker.settings import Settings
from tests.factories import FakeObjectStore, sha256_of

pytestmark = [pytest.mark.asyncio, pytest.mark.slow]

GOLDEN = Path(__file__).parent / "golden"

#: The Phase 07 budget: a 50-page text PDF reaches `ready` in under 20 seconds
#: on a four-core machine. Asserted rather than aspired to.
FIFTY_PAGE_BUDGET_SECONDS = 20.0

#: CI machines are not developer machines. The budget above is the acceptance
#: criterion; this is the allowance the assertion runs with so that a shared
#: runner having a bad minute is not a red build. A real regression is a
#: multiple of this, not a fraction.
BUDGET_SLACK = 5.0 if os.getenv("CI") else 3.0


async def parse(
    name: str, *, settings: Settings, fixtures_dir: Path, org_id: str = "org_test"
) -> tuple[ParseArtifact, FakeObjectStore]:
    """Run the whole pipeline over one fixture, with storage faked and nothing else."""
    source = fixtures_dir / name
    store = FakeObjectStore(source=source)
    artifact = await parse_document(
        store=store,
        settings=settings,
        org_id=org_id,
        document_id="doc_fixture",
        storage_key=f"orgs/{org_id}/documents/doc_fixture/original.pdf",
        content_hash=sha256_of(source),
        on_stage=None,
    )
    return artifact, store


def normalized(text: str) -> str:
    """Collapse whitespace, so a rewrap is not a failure and a rewording is."""
    return re.sub(r"\s+", " ", text).strip()


def assert_golden(name: str, actual: str) -> None:
    path = GOLDEN / name
    if os.environ.get("KONUSBITR_UPDATE_GOLDEN"):
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(actual, encoding="utf-8")
        pytest.skip(f"rewrote {path.name}; re-run without KONUSBITR_UPDATE_GOLDEN")
    if not path.is_file():
        pytest.fail(
            f"{path} is missing. Generate it with KONUSBITR_UPDATE_GOLDEN=1 and read the diff."
        )
    assert normalized(actual) == normalized(path.read_text(encoding="utf-8"))


# ── The good fixtures ────────────────────────────────────────────────────────


async def test_a_clean_text_pdf_parses_faithfully(settings: Settings, fixtures_dir: Path) -> None:
    artifact, _store = await parse(
        "clean-text-10p.pdf", settings=settings, fixtures_dir=fixtures_dir
    )

    assert artifact.page_count == 10
    assert len(artifact.pages) == 10
    assert artifact.contents, "a text PDF must produce elements"
    # The heading this repository wrote onto page one, back out again.
    assert "Clean Text Fixture" in artifact.markdown
    assert_golden("clean-text-10p.md", artifact.markdown)


async def test_every_element_is_locatable(settings: Settings, fixtures_dir: Path) -> None:
    """The acceptance criterion, stated as one assertion over every element.

    A page number in range and a box inside that page is the minimum for a
    citation to be clickable at all; without it the viewer has nowhere to
    scroll and nothing to draw.
    """
    artifact, _store = await parse(
        "clean-text-10p.pdf", settings=settings, fixtures_dir=fixtures_dir
    )
    by_page = {page.page_no: page for page in artifact.pages}

    for element in artifact.contents:
        assert 1 <= element.page <= artifact.page_count
        page = by_page[element.page]
        box = element.bbox
        assert 0 <= box.x0 < box.x1 <= page.width + 0.01
        assert 0 <= box.y0 < box.y1 <= page.height + 0.01


async def test_a_heading_near_the_top_of_the_page_has_a_small_y(
    settings: Settings, fixtures_dir: Path
) -> None:
    """The inverted-axis assertion, against a real parse.

    The generator draws the section heading 72 points below the top of the
    page. A flipped y axis would put it 72 points above the bottom, which is
    entirely plausible output and completely wrong.
    """
    artifact, _store = await parse(
        "clean-text-10p.pdf", settings=settings, fixtures_dir=fixtures_dir
    )

    headings = [
        element
        for element in artifact.contents
        if element.type is ElementType.heading and element.page == 1
    ]
    assert headings, "the fixture opens with a heading"
    assert headings[0].bbox.y0 < 120.0


async def test_tables_survive_as_markdown_and_as_json(
    settings: Settings, fixtures_dir: Path
) -> None:
    """Both representations, on one element, never split across two."""
    artifact, _store = await parse(
        "tables-financial.pdf", settings=settings, fixtures_dir=fixtures_dir
    )

    tables = [element for element in artifact.contents if element.type is ElementType.table]
    assert len(tables) == 2, "the fixture has a revenue table and a headcount table"

    revenue = tables[0]
    assert revenue.table is not None
    assert "Segment" in revenue.table.headers
    flattened = [cell for row in revenue.table.rows for cell in row]
    assert "Subscriptions" in flattened
    assert "5,860" in flattened

    assert "|" in revenue.markdown and "Subscriptions" in revenue.markdown
    # The table reads as a table in the document markdown too, which is what
    # the model sees in context.
    assert "Subscriptions" in artifact.markdown


async def test_a_two_column_paper_is_read_down_the_columns(
    settings: Settings, fixtures_dir: Path
) -> None:
    """Reading order, which is the whole reason for a layout-aware parser.

    A parser that reads across the gutter interleaves the two columns, so the
    first paragraph of the introduction is followed by the first paragraph of
    whatever is beside it. The golden file is what notices.
    """
    artifact, _store = await parse(
        "two-column-paper.pdf", settings=settings, fixtures_dir=fixtures_dir
    )

    assert "Introduction" in artifact.markdown
    assert artifact.markdown.index("1. Introduction") < artifact.markdown.index("2. Method")
    assert_golden("two-column-paper.md", artifact.markdown)


async def test_a_rotated_a4_page_comes_back_in_the_visible_frame(
    settings: Settings, fixtures_dir: Path
) -> None:
    """Rotation and a non-Letter page size, together, on a real document.

    A4 is 595 by 842. The rotated page must report 842 by 595 — the dimensions a
    person reading it sees — and its heading must still be near the top of it.
    """
    artifact, _store = await parse("rotated-a4.pdf", settings=settings, fixtures_dir=fixtures_dir)

    upright, rotated, _last = artifact.pages
    assert (round(upright.width), round(upright.height)) == (595, 842)
    assert rotated.rotation == 90
    assert (round(rotated.width), round(rotated.height)) == (842, 595)

    on_rotated = [element for element in artifact.contents if element.page == 2]
    assert on_rotated, "the rotated page has content"
    for element in on_rotated:
        assert element.bbox.x1 <= rotated.width + 0.01
        assert element.bbox.y1 <= rotated.height + 0.01
    assert min(element.bbox.y0 for element in on_rotated) < rotated.height / 2


async def test_a_thumbnail_exists_for_every_page(settings: Settings, fixtures_dir: Path) -> None:
    """The acceptance criterion, and the shape the library grid depends on."""
    artifact, store = await parse(
        "rotated-a4.pdf", settings=settings, fixtures_dir=fixtures_dir, org_id="org_thumbs"
    )

    assert len(store.uploads) == artifact.page_count
    for page in artifact.pages:
        assert page.thumbnail_key is not None
        assert page.thumbnail_key.startswith("orgs/org_thumbs/documents/doc_fixture/thumbnails/")
        assert store.content_types[page.thumbnail_key] == "image/webp"
        # RIFF….WEBP — the file really is what the content type claims.
        body = store.uploads[page.thumbnail_key]
        assert body[:4] == b"RIFF" and body[8:12] == b"WEBP"


async def test_a_thumbnail_is_bounded_by_its_longest_edge(
    settings: Settings, fixtures_dir: Path
) -> None:
    from io import BytesIO

    from PIL import Image

    artifact, store = await parse("rotated-a4.pdf", settings=settings, fixtures_dir=fixtures_dir)

    for page in artifact.pages:
        assert page.thumbnail_key is not None
        with Image.open(BytesIO(store.uploads[page.thumbnail_key])) as image:
            assert max(image.size) == pytest.approx(settings.worker_thumbnail_max_edge, abs=2)
            # The thumbnail is of the page a reader sees, so its aspect ratio
            # matches the visible frame rather than the stored one.
            assert image.width > image.height if page.width > page.height else True


# ── The bad fixtures ─────────────────────────────────────────────────────────


@pytest.mark.parametrize(
    ("name", "code"),
    [
        ("malformed.pdf", JobErrorCode.corrupt_document),
        ("encrypted.pdf", JobErrorCode.encrypted_document),
        ("scanned-no-text.pdf", JobErrorCode.needs_ocr),
    ],
)
async def test_a_bad_fixture_fails_with_its_own_code(
    name: str, code: JobErrorCode, settings: Settings, fixtures_dir: Path
) -> None:
    """Distinct codes, distinct messages, and no attempt spent on any of them.

    All three are terminal, so the retry policy treats them identically — which
    means the only thing that turns on the difference is what the person who
    uploaded the file is told. Telling somebody with a password-protected PDF
    that their file is corrupt sends them looking for the wrong fix.
    """
    with pytest.raises(JobFailure) as raised:
        await parse(name, settings=settings, fixtures_dir=fixtures_dir)

    assert raised.value.code is code
    assert raised.value.retryable is False
    assert raised.value.message and raised.value.message[0].isupper()


async def test_the_scanned_message_says_where_ocr_is_coming_from(
    settings: Settings, fixtures_dir: Path
) -> None:
    """A refusal that does not say what to do instead is just a dead end."""
    with pytest.raises(JobFailure) as raised:
        await parse("scanned-no-text.pdf", settings=settings, fixtures_dir=fixtures_dir)

    assert "scan" in raised.value.message.lower()
    assert "advanced" in raised.value.message.lower()


async def test_a_page_ceiling_is_enforced_before_any_parsing(
    settings: Settings, fixtures_dir: Path
) -> None:
    """`MAX_PAGES` is an operator's ceiling, and it is cheap to check."""
    capped = settings.model_copy(update={"max_pages": 3})

    with pytest.raises(JobFailure) as raised:
        await parse("clean-text-10p.pdf", settings=capped, fixtures_dir=fixtures_dir)

    assert raised.value.code is JobErrorCode.too_many_pages
    assert "10" in raised.value.message and "3" in raised.value.message


# ── The budget ───────────────────────────────────────────────────────────────


async def test_fifty_pages_parse_inside_the_budget(settings: Settings, fixtures_dir: Path) -> None:
    """The performance acceptance criterion, as a test rather than a hope.

    Per-stage timings are attached to the artifact and printed on failure, so a
    regression says *which* stage slowed down rather than only that something
    did — the difference between a five-minute diagnosis and an afternoon.
    """
    started = time.perf_counter()
    artifact, _store = await parse("text-50p.pdf", settings=settings, fixtures_dir=fixtures_dir)
    elapsed = time.perf_counter() - started

    assert artifact.page_count == 50
    assert elapsed < FIFTY_PAGE_BUDGET_SECONDS * BUDGET_SLACK, (
        f"50 pages took {elapsed:.1f}s against a {FIFTY_PAGE_BUDGET_SECONDS}s budget; "
        f"per-stage milliseconds: {artifact.timings}"
    )
