/**
 * `@konusbitr/shared` — the single source of truth for every type that crosses a
 * boundary: web ↔ API, API ↔ Python worker, and the generated SDK.
 *
 * Schemas here are Zod v4. The Python worker's pydantic models are generated
 * from them, so a change in this package is a change to the cross-language
 * contract.
 */

export {
  API_ERROR_CODES,
  API_ERROR_STATUS,
  API_JOB_KINDS,
  API_JOB_STATUSES,
  type ApiDocument,
  ApiDocumentSchema,
  type ApiErrorBody,
  type ApiErrorCode,
  ApiErrorCodeSchema,
  ApiErrorSchema,
  type ApiJob,
  type ApiJobKind,
  ApiJobKindSchema,
  ApiJobSchema,
  type ApiJobStatus,
  ApiJobStatusSchema,
  type AskRequest,
  AskRequestSchema,
  type AskResponse,
  AskResponseSchema,
  type AsyncAccepted,
  AsyncAcceptedSchema,
  AsyncOptionsSchema,
  type ChatWithAllPdfsRequest,
  ChatWithAllPdfsRequestSchema,
  type ChatWithPdfRequest,
  ChatWithPdfRequestSchema,
  type ChatWithPdfResponse,
  ChatWithPdfResponseSchema,
  DeleteDocumentResponseSchema,
  DocumentInputSchema,
  EXTRACT_SCHEMA_LIMITS,
  EXTRACT_SMALL_SCHEMA_FIELDS,
  EXTRACT_WHOLE_DOCUMENT_MAX_PAGES,
  type ExtractRequest,
  ExtractRequestSchema,
  type ExtractResponse,
  ExtractResponseSchema,
  LegacyReferenceSchema,
  normalizeAliases,
  type PageRange,
  PageRangeSchema,
  type ParsedElement,
  ParsedElementSchema,
  type ParseRequest,
  ParseRequestSchema,
  type ParseResponse,
  ParseResponseSchema,
  ParseSettingsInputSchema,
  REQUEST_ALIASES,
  type SplitRequest,
  SplitRequestSchema,
  type SplitResponse,
  SplitResponseSchema,
} from './api-v2.js';
export {
  type ChatMessageView,
  ChatMessageViewSchema,
  type ChatRequest,
  ChatRequestSchema,
  type ChatRole,
  ChatRoleSchema,
  type ConversationScope,
  ConversationScopeSchema,
  type ConversationView,
  ConversationViewSchema,
  type CreateConversationRequest,
  CreateConversationRequestSchema,
  type UpdateConversationRequest,
  UpdateConversationRequestSchema,
} from './chat.js';
export {
  CHUNK_KINDS,
  CHUNKING_DEFAULTS,
  type ChunkKind,
  ChunkKindSchema,
  type ChunkMeta,
  ChunkMetaSchema,
  type ChunkPage,
  ChunkPageSchema,
  type ChunkTable,
  type ChunkTableCell,
  ChunkTableCellSchema,
  ChunkTableSchema,
  type ChunkView,
  ChunkViewSchema,
  formatSectionPath,
  SECTION_PATH_SEPARATOR,
  TRUNCATION_MARKER,
  unionChunkPages,
} from './chunk.js';
export {
  type BoundingBox,
  BoundingBoxSchema,
  type Citation,
  CitationSchema,
  type RejectedCitation,
  RejectedCitationSchema,
} from './citation.js';
export {
  askCost,
  CREDIT_RATES,
  CREDIT_REASONS,
  type CreditReason,
  extractCost,
  MINIMUM_BILLED_PAGES,
  parseCost,
  splitCost,
} from './credits.js';
export {
  ANSWERABLE_DOCUMENT_STATUSES,
  DOCUMENT_STATUSES,
  type DocumentStatus,
  DocumentStatusSchema,
  isAnswerableDocumentStatus,
  isTerminalDocumentStatus,
  TERMINAL_DOCUMENT_STATUSES,
} from './document.js';
export {
  CREDITS_MODES,
  type Env,
  EnvSchema,
  EnvSchemaChecked,
  EnvValidationError,
  isRoleConfigured,
  loadEnv,
  NODE_ENVS,
  parseEnv,
  resetEnvCache,
  roleModel,
  roleProvider,
} from './env.js';
export {
  DEFAULT_PAGE_BATCH_SIZE,
  isRetryableJobError,
  isTerminalJobStage,
  JOB_CHECKPOINT_VERSION,
  JOB_ERROR_CODES,
  JOB_PAYLOAD_VERSION,
  JOB_STAGES,
  JOB_TYPES,
  type JobCheckpoint,
  JobCheckpointSchema,
  type JobErrorCode,
  JobErrorCodeSchema,
  type JobPayload,
  JobPayloadSchema,
  type JobProgress,
  JobProgressSchema,
  type JobStage,
  JobStageSchema,
  type JobType,
  JobTypeSchema,
  type SplitInstructions,
  SplitInstructionsSchema,
  type SplitRange,
  SplitRangeSchema,
  STAGE_PERCENT,
  TERMINAL_JOB_ERROR_CODES,
  TERMINAL_JOB_STAGES,
} from './job.js';
export {
  CLOUD_LLM_PROVIDERS,
  DEFAULT_CHAT_MODELS,
  DEFAULT_EMBEDDING_MODELS,
  DEFAULT_RERANK_MODELS,
  DEFAULT_VISION_MODELS,
  EMBEDDING_DIMENSIONS,
  isLocalProvider,
  LLM_PROVIDERS,
  type LlmProvider,
  LlmProviderSchema,
  LOCAL_LLM_PROVIDERS,
  MODEL_ROLES,
  type ModelRole,
  ModelRoleSchema,
  PROVIDERS_WITHOUT_EMBEDDINGS,
  type ProviderMeta,
  providerCanEmbed,
  SUPPORTED_EXTERNAL_PROVIDERS,
} from './models.js';
export { type ExtractedImage, ExtractedImageSchema } from './parse-artifact.js';

export {
  canonicalizeParseSettings,
  DEFAULT_PARSE_SETTINGS,
  type ParseQuality,
  ParseQualitySchema,
  type ParseSettings,
  ParseSettingsSchema,
  parseSettingsHashInput,
} from './parse-settings.js';
export {
  CANCEL_KEY_PREFIX,
  CANCEL_TTL_SECONDS,
  cancelKey,
  DEAD_LETTER_MAX_LENGTH,
  JOBS_CONSUMER_GROUP,
  JOBS_DEAD_LETTER,
  JOBS_RETRY_ZSET,
  JOBS_STREAM,
  JOBS_STREAM_FIELD,
  JOBS_STREAM_MAX_LENGTH,
  PROGRESS_CHANNEL_PREFIX,
  progressChannel,
} from './queue.js';
export {
  RATE_LIMIT_LIMIT_HEADER,
  RATE_LIMIT_REMAINING_HEADER,
  RATE_LIMIT_RESET_HEADER,
  RATE_LIMIT_SCOPE_HEADER,
  type RateLimitDecision,
  type RateLimitScope,
  RETRY_AFTER_HEADER,
  rateLimitHeaders,
} from './rate-limit.js';
export {
  type CompleteUploadRequest,
  CompleteUploadRequestSchema,
  type CreateDocumentRequest,
  CreateDocumentRequestSchema,
  type CreateFromUrlRequest,
  CreateFromUrlRequestSchema,
  DEFAULT_MAX_UPLOAD_BYTES,
  type DocumentView,
  DocumentViewSchema,
  type PresignRequest,
  PresignRequestSchema,
  type PresignResponse,
  PresignResponseSchema,
  type RenameDocumentRequest,
  RenameDocumentRequestSchema,
  SUPPORTED_UPLOAD_MIMES,
  sanitizeFilename,
  UPLOAD_ACCEPT_ATTRIBUTE,
  UPLOAD_KINDS,
  type UploadKind,
  uploadKindForFilename,
  uploadKindForMime,
} from './upload.js';
export {
  DEFAULT_LOCAL_VLM_MODEL,
  DEFAULT_MAX_VLM_PAGES_PER_JOB,
  DEFAULT_TIER_FALLBACK_THRESHOLD,
  DEFAULT_VLM_DPI,
  type EstimateCostRequest,
  EstimateCostRequestSchema,
  type EstimateCostResponse,
  EstimateCostResponseSchema,
  type EstimateInput,
  estimateVlmCost,
  FALLBACK_PRICE,
  formatUsd,
  imageTokensPerPage,
  PIXELS_PER_IMAGE_TOKEN,
  VLM_COMPLETION_TOKENS_PER_PAGE,
  VLM_IMAGE_MAX_EDGE,
  VLM_MODEL_PRICES,
  VLM_PAGE_CONCURRENCY,
  VLM_PROMPT_TOKENS,
  VLM_SECONDS_PER_PAGE,
  type VlmCostEstimate,
} from './vlm.js';
export {
  formatWebhookSignature,
  parseWebhookSignature,
  WEBHOOK_ATTEMPT_HEADER,
  WEBHOOK_BACKOFF_MS,
  WEBHOOK_ID_HEADER,
  WEBHOOK_MAX_ATTEMPTS,
  WEBHOOK_SIGNATURE_HEADER,
  WEBHOOK_SIGNATURE_VERSION,
  WEBHOOK_TIMEOUT_MS,
  WEBHOOK_TIMESTAMP_HEADER,
  WEBHOOK_TIMESTAMP_TOLERANCE_SECONDS,
  webhookSigningPayload,
} from './webhooks.js';
