"""The TypeScript ↔ Python contract. **Generated — do not edit.**

Every payload that crosses the seam between the two runtimes is defined once, in
Zod, in ``packages/shared``. This module is produced from those definitions by
``pnpm codegen``; CI regenerates it and fails on any diff, so editing it here
cannot survive review and editing the Zod without regenerating cannot merge.

To change a payload: edit ``packages/shared/src/job.ts`` (or ``queue.ts`` for
the Redis key names), run ``pnpm codegen``, and commit both halves together.
"""
# generated by datamodel-codegen:
#   filename:  contract.schema.json

from __future__ import annotations

from enum import StrEnum
from typing import Annotated, Literal

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field


class DocumentStatus(StrEnum):
    """
    Lifecycle of a document from upload to queryable.
    """

    queued = "queued"
    parsing = "parsing"
    ocr = "ocr"
    embedding = "embedding"
    ready = "ready"
    failed = "failed"


class JobStage(StrEnum):
    """
    Pipeline stage a job is currently in.
    """

    queued = "queued"
    fetching = "fetching"
    validating = "validating"
    parsing = "parsing"
    ocr = "ocr"
    chunking = "chunking"
    embedding = "embedding"
    persisting = "persisting"
    ready = "ready"
    failed = "failed"


class JobType(StrEnum):
    """
    What a worker is being asked to do.
    """

    parse = "parse"
    chunk_embed = "chunk_embed"
    split = "split"
    reindex = "reindex"


class JobErrorCode(StrEnum):
    """
    Why a job failed, in a form both runtimes switch on.
    """

    invalid_payload = "invalid_payload"
    unknown_job_type = "unknown_job_type"
    unsupported_version = "unsupported_version"
    document_missing = "document_missing"
    object_missing = "object_missing"
    content_hash_mismatch = "content_hash_mismatch"
    corrupt_document = "corrupt_document"
    unsupported_format = "unsupported_format"
    encrypted_document = "encrypted_document"
    too_many_pages = "too_many_pages"
    storage_unavailable = "storage_unavailable"
    database_unavailable = "database_unavailable"
    model_unavailable = "model_unavailable"
    model_timeout = "model_timeout"
    out_of_memory = "out_of_memory"
    timeout = "timeout"
    cancelled = "cancelled"
    internal = "internal"


class ParseQuality(StrEnum):
    """
    Parser tier.
    """

    standard = "standard"
    advanced = "advanced"


class ParseSettings(BaseModel):
    """
    Everything that can change the bytes of a parse result; hashed into settings_hash.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    quality: ParseQuality
    langList: list[str]
    llm: bool


class JobPayload(BaseModel):
    """
    A job as it is written to the konusbitr:jobs stream by the web app.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    v: Literal[1]
    jobId: Annotated[str, Field(min_length=1)]
    type: JobType
    orgId: Annotated[str, Field(min_length=1)]
    documentId: Annotated[str, Field(min_length=1)]
    storageKey: Annotated[str, Field(min_length=1)]
    contentHash: Annotated[str, Field(pattern="^[0-9a-f]{64}$")]
    settings: ParseSettings
    attempt: Annotated[int, Field(gt=0)]
    enqueuedAt: AwareDatetime


class JobProgress(BaseModel):
    """
    A progress event published on konusbitr:progress:{documentId} and relayed over SSE.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    jobId: Annotated[str, Field(min_length=1)]
    documentId: Annotated[str, Field(min_length=1)]
    stage: JobStage
    percent: Annotated[float, Field(ge=0.0, le=100.0)]
    message: str | None = None
    errorCode: JobErrorCode | None = None
    at: AwareDatetime


# ─── Transport constants ─────────────────────────────────────────────────────
#
# Generated from packages/shared/src/queue.ts and src/job.ts. A queue name is
# part of the contract: a worker listening on the wrong stream is as broken as
# one parsing the wrong JSON, and much harder to notice.

#: The stream the web app appends jobs to with XADD.
JOBS_STREAM = "konusbitr:jobs"

#: The consumer group every worker joins, so one delivery goes to one worker.
JOBS_CONSUMER_GROUP = "konusbitr:workers"

#: Jobs waiting out a backoff, scored by the epoch millisecond they are due.
JOBS_RETRY_ZSET = "konusbitr:jobs:retry"

#: Where a job goes when no number of attempts could make it succeed.
JOBS_DEAD_LETTER = "konusbitr:jobs:dead"

#: Approximate cap on the stream, applied on every append.
JOBS_STREAM_MAX_LENGTH = 10000

#: Cap on the dead-letter list; the oldest entries are dropped.
DEAD_LETTER_MAX_LENGTH = 1000

#: The field inside a stream entry that carries the JSON payload.
JOBS_STREAM_FIELD = "payload"

#: Prefix of the per-document progress channel. Read over SSE, never a socket.
PROGRESS_CHANNEL_PREFIX = "konusbitr:progress:"

#: Envelope version this build understands. Anything else is dead-lettered.
JOB_PAYLOAD_VERSION = 1


def progress_channel(document_id: str) -> str:
    """The channel a document's progress is published on."""
    return f"{PROGRESS_CHANNEL_PREFIX}{document_id}"


#: The percentage a stage is worth on entry, so a reconnecting browser that
#: replays from the jobs row sees the same bar the live events were drawing.
STAGE_PERCENT: dict[JobStage, int] = {
    JobStage.queued: 0,
    JobStage.fetching: 5,
    JobStage.validating: 10,
    JobStage.parsing: 20,
    JobStage.ocr: 45,
    JobStage.chunking: 70,
    JobStage.embedding: 85,
    JobStage.persisting: 95,
    JobStage.ready: 100,
    JobStage.failed: 100,
}

#: Stages after which no further progress events are published.
TERMINAL_JOB_STAGES: frozenset[JobStage] = frozenset(
    (
        JobStage.ready,
        JobStage.failed,
    )
)

#: The error codes no number of attempts will fix. Everything else is retryable.
TERMINAL_JOB_ERROR_CODES: frozenset[JobErrorCode] = frozenset(
    (
        JobErrorCode.invalid_payload,
        JobErrorCode.unknown_job_type,
        JobErrorCode.unsupported_version,
        JobErrorCode.document_missing,
        JobErrorCode.object_missing,
        JobErrorCode.content_hash_mismatch,
        JobErrorCode.corrupt_document,
        JobErrorCode.unsupported_format,
        JobErrorCode.encrypted_document,
        JobErrorCode.too_many_pages,
    )
)


def is_retryable(code: JobErrorCode) -> bool:
    """Whether an attempt is worth spending on this failure."""
    return code not in TERMINAL_JOB_ERROR_CODES
