import { describe, expect, it } from 'vitest';
import { guestPlugin, isGuestEmail } from '@/lib/auth/guest';

describe('guest authentication', () => {
  describe('isGuestEmail', () => {
    it('identifies guest email addresses generated by the plugin', () => {
      expect(isGuestEmail('guest-1234abcd@konusbitr.local')).toBe(true);
      expect(isGuestEmail('guest-test@konusbitr.local')).toBe(true);
    });

    it('rejects regular users, dev users, and missing input', () => {
      expect(isGuestEmail('dev@konusbitr.local')).toBe(false);
      expect(isGuestEmail('person@example.com')).toBe(false);
      expect(isGuestEmail('guest-1234abcd@otherdomain.com')).toBe(false);
      expect(isGuestEmail('notguest-123@konusbitr.local')).toBe(false);
      expect(isGuestEmail(null)).toBe(false);
      expect(isGuestEmail(undefined)).toBe(false);
      expect(isGuestEmail('')).toBe(false);
    });
  });

  describe('guestPlugin', () => {
    it('defines the guest authentication plugin with the expected endpoint', () => {
      const plugin = guestPlugin();
      expect(plugin.id).toBe('guest');
      expect(plugin.endpoints).toBeDefined();
      expect(plugin.endpoints?.signInGuest).toBeDefined();
      const endpoint = plugin.endpoints?.signInGuest as
        | { options?: { disableBody?: boolean } }
        | undefined;
      expect(endpoint?.options?.disableBody).toBe(true);
    });
  });
});
