"""``konusbitr`` — the Python client for the Konusbitr API.

::

    from konusbitr import Konusbitr

    client = Konusbitr(base_url="https://konusbitr.example.com", api_key="kb_…")

    doc = client.parse(url="https://example.com/report.pdf")
    answer = client.ask(docId=doc["docId"], question="What is the total?")

    for citation in answer["citations"]:
        print(citation["page"], citation["quote"])

The types and the operation table in :mod:`konusbitr._generated` come from the
API's own OpenAPI document and are regenerated by ``make generate``; CI fails on
drift. The client itself is written by hand, because retries, backoff and job
polling are not things a specification describes.
"""

from konusbitr._generated import API_VERSION
from konusbitr.client import AsyncKonusbitr, Konusbitr
from konusbitr.errors import JobFailedError, KonusbitrError, RateLimitError

__all__ = [
    "API_VERSION",
    "AsyncKonusbitr",
    "JobFailedError",
    "Konusbitr",
    "KonusbitrError",
    "RateLimitError",
]

__version__ = "0.1.0"
